runtime: nodejs16
env: standard
service: ${{ env.GCLOUD_PROJECT_SERVICE_ID }}
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
build_env_variables:
  GOOGLE_NODE_RUN_SCRIPTS: ''
env_variables:
  CLOUD_SERVICE_PROVIDER: 'gcloud'
