steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      echo $'\n  NEXT_PUBLIC_CONTRACT_ADDRESS: '$$NEXT_PUBLIC_CONTRACT_ADDRESS >> app.yaml
      gcloud -q app deploy

  secretEnv: ['NEXT_PUBLIC_CONTRACT_ADDRESS']
availableSecrets:
  secretManager:
  - versionName: projects/joc-token-vesting-dev/secrets/ADMINISTRATOR_NEXT_PUBLIC_CONTRACT_ADDRESS/versions/latest
    env: 'NEXT_PUBLIC_CONTRACT_ADDRESS'
timeout: '1600s'