name: Publish docker container sample
run-name: Deploy ${{ github.ref_name }} to dev environment by @${{ github.actor }}
on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./publish-docker
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build & Publish Image'
        run: |
          docker build . --tag ghcr.io/0xcuonghx/docker-sample:latest
          docker push ghcr.io/0xcuonghx/docker-sample:latest
