name: Test secrets manager
run-name: Deploy ${{ github.ref_name }} to dev environment by @${{ github.actor }}
on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

env:
  GCLOUD_PROJECT_ID: joc-token-vesting-dev

jobs:
  secrets-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v1'
        with:
          secrets: |-
            NEXT_PUBLIC_CHAIN_ID:${{ env.GCLOUD_PROJECT_ID }}/ADMINISTRATOR_NEXT_PUBLIC_CHAIN_ID
      - name: logs
        run: echo "${{ steps.secrets.outputs.NEXT_PUBLIC_CHAIN_ID }}"

        